import type { TranscriptSegment, WordTimestamp } from '@shorts/shared';
import { getSubtitleTheme, type SubtitleThemeId } from '@shorts/video-config';

/**
 * Convert seconds (float) to ASS timestamp format: H:MM:SS.CC (centiseconds)
 */
export function formatAssTime(seconds: number): string {
  const s = Math.max(0, seconds);
  const hrs = Math.floor(s / 3600);
  const mins = Math.floor((s % 3600) / 60);
  const secs = Math.floor(s % 60);
  const centis = Math.floor((s % 1) * 100);

  return `${hrs}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}.${String(centis).padStart(2, '0')}`;
}

/**
 * Convert seconds to SRT timestamp format: HH:MM:SS,mmm
 */
export function formatSrtTime(seconds: number): string {
  const s = Math.max(0, seconds);
  const hrs = Math.floor(s / 3600);
  const mins = Math.floor((s % 3600) / 60);
  const secs = Math.floor(s % 60);
  const millis = Math.floor((s % 1) * 1000);

  return `${String(hrs).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')},${String(millis).padStart(3, '0')}`;
}

/**
 * Convert seconds to VTT timestamp format: HH:MM:SS.mmm
 */
export function formatVttTime(seconds: number): string {
  const s = Math.max(0, seconds);
  const hrs = Math.floor(s / 3600);
  const mins = Math.floor((s % 3600) / 60);
  const secs = Math.floor(s % 60);
  const millis = Math.floor((s % 1) * 1000);

  return `${String(hrs).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}.${String(millis).padStart(3, '0')}`;
}

export interface AssGeneratorOptions {
  themeId: SubtitleThemeId;
  playResX?: number; // 1080 default
  playResY?: number; // 1920 default
  clipStartTime?: number; // offset to align with clip boundary
}

/**
 * Generates an Advanced SubStation Alpha (.ass) subtitle file content
 * with true karaoke word highlights, high-energy stroke, and platform safe margins.
 */
export function generateAssSubtitles(
  segments: TranscriptSegment[],
  options: AssGeneratorOptions
): string {
  const theme = getSubtitleTheme(options.themeId);
  const playResX = options.playResX || 1080;
  const playResY = options.playResY || 1920;
  const clipStart = options.clipStartTime || 0;

  // Scale font size proportionally if export resolution is 2K (1440) or 4K (2160)
  const scale = playResX / 1080;
  const scaledFontSize = Math.round(theme.fontSizeAss * scale);
  const scaledMarginV = Math.round(theme.marginV * scale);
  const scaledMarginL = Math.round(theme.marginL * scale);
  const scaledMarginR = Math.round(theme.marginR * scale);
  const scaledOutline = Math.round(theme.outlineWidth * scale);
  const scaledShadow = Math.round(theme.shadowDepth * scale);

  const header = `[Script Info]
; Script generated by AI-Powered Shorts Engine
ScriptType: v4.00+
PlayResX: ${playResX}
PlayResY: ${playResY}
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${theme.fontFamily.split(',')[0]},${scaledFontSize},${theme.primaryColorAss},${theme.secondaryColorAss},${theme.outlineColorAss},${theme.backColorAss},-1,0,0,0,100,100,0,0,1,${scaledOutline},${scaledShadow},${theme.alignment},${scaledMarginL},${scaledMarginR},${scaledMarginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const dialogueLines: string[] = [];

  for (const seg of segments) {
    if (!seg.words || seg.words.length === 0) {
      if (seg.text && seg.text.trim()) {
        const start = formatAssTime(Math.max(0, seg.start - clipStart));
        const end = formatAssTime(Math.max(0, seg.end - clipStart));
        const text = theme.capitalization === 'uppercase' ? seg.text.toUpperCase() : seg.text;
        dialogueLines.push(`Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`);
      }
      continue;
    }

    // Group words into bite-sized short-form caption batches (e.g. 2 to 4 words per line)
    const wordsPerGroup = theme.wordsPerCaptionGroup || 3;
    for (let i = 0; i < seg.words.length; i += wordsPerGroup) {
      const groupWords = seg.words.slice(i, i + wordsPerGroup);
      const groupStart = Math.max(0, groupWords[0].start - clipStart);
      const groupEnd = Math.max(0, groupWords[groupWords.length - 1].end - clipStart);

      // Karaoke tags construction: {\k<duration_in_centiseconds>}word
      let formattedText = '';
      if (theme.animationStyle === 'karaoke-pop' || theme.id === 'karaoke-highlight') {
        for (const w of groupWords) {
          const durationCentis = Math.max(5, Math.round((w.end - w.start) * 100));
          const cleanWord = theme.capitalization === 'uppercase' ? w.word.toUpperCase() : w.word;
          formattedText += `{\\k${durationCentis}}${cleanWord} `;
        }
      } else {
        const joined = groupWords.map((w) => w.word).join(' ');
        formattedText = theme.capitalization === 'uppercase' ? joined.toUpperCase() : joined;
      }

      dialogueLines.push(
        `Dialogue: 0,${formatAssTime(groupStart)},${formatAssTime(groupEnd)},Default,,0,0,0,,${formattedText.trim()}`
      );
    }
  }

  return header + dialogueLines.join('\n');
}

/**
 * Generate standard SRT format subtitles
 */
export function generateSrtSubtitles(
  segments: TranscriptSegment[],
  clipStartTime: number = 0
): string {
  let srt = '';
  let index = 1;

  for (const seg of segments) {
    if (!seg.text || !seg.text.trim()) continue;
    const start = formatSrtTime(Math.max(0, seg.start - clipStartTime));
    const end = formatSrtTime(Math.max(0, seg.end - clipStartTime));

    srt += `${index}\n${start} --> ${end}\n${seg.text.trim()}\n\n`;
    index++;
  }

  return srt;
}

/**
 * Generate WebVTT format subtitles for HTML5 video player previews
 */
export function generateVttSubtitles(
  segments: TranscriptSegment[],
  clipStartTime: number = 0
): string {
  let vtt = 'WEBVTT\n\n';

  for (const seg of segments) {
    if (!seg.text || !seg.text.trim()) continue;
    const start = formatVttTime(Math.max(0, seg.start - clipStartTime));
    const end = formatVttTime(Math.max(0, seg.end - clipStartTime));

    vtt += `${start} --> ${end}\n${seg.text.trim()}\n\n`;
  }

  return vtt;
}
